/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java4lab;


/**
 *
 * @author Денис
 */
public class MainWindow extends javax.swing.JFrame {

    private final double[] constarray = {23, 1.3, 18, -6, 20, 1256};
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        task1Panel = new javax.swing.JPanel();
        task1RunButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        task1TextArea = new javax.swing.JTextArea();
        task2Panel = new javax.swing.JPanel();
        task3Panel = new javax.swing.JPanel();
        task1Button = new javax.swing.JButton();
        task2Button = new javax.swing.JButton();
        task3Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setLayout(new java.awt.CardLayout());

        task1RunButton.setText("Run");
        task1RunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task1RunButtonActionPerformed(evt);
            }
        });

        task1TextArea.setColumns(20);
        task1TextArea.setRows(5);
        jScrollPane1.setViewportView(task1TextArea);

        javax.swing.GroupLayout task1PanelLayout = new javax.swing.GroupLayout(task1Panel);
        task1Panel.setLayout(task1PanelLayout);
        task1PanelLayout.setHorizontalGroup(
            task1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(task1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(task1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(task1PanelLayout.createSequentialGroup()
                        .addComponent(task1RunButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        task1PanelLayout.setVerticalGroup(
            task1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(task1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(task1RunButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(task1Panel, "card2");

        javax.swing.GroupLayout task2PanelLayout = new javax.swing.GroupLayout(task2Panel);
        task2Panel.setLayout(task2PanelLayout);
        task2PanelLayout.setHorizontalGroup(
            task2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        task2PanelLayout.setVerticalGroup(
            task2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        mainPanel.add(task2Panel, "card3");

        javax.swing.GroupLayout task3PanelLayout = new javax.swing.GroupLayout(task3Panel);
        task3Panel.setLayout(task3PanelLayout);
        task3PanelLayout.setHorizontalGroup(
            task3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        task3PanelLayout.setVerticalGroup(
            task3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        mainPanel.add(task3Panel, "card4");

        task1Button.setText("jButton1");
        task1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task1ButtonActionPerformed(evt);
            }
        });

        task2Button.setText("jButton2");
        task2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task2ButtonActionPerformed(evt);
            }
        });

        task3Button.setText("jButton3");
        task3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task3ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(task1Button)
                .addGap(109, 109, 109)
                .addComponent(task2Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(task3Button)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(task1Button)
                    .addComponent(task2Button)
                    .addComponent(task3Button))
                .addGap(18, 18, 18)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void task1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task1ButtonActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(task1Panel);
        mainPanel.repaint(); mainPanel.revalidate();
    }//GEN-LAST:event_task1ButtonActionPerformed

    private void task2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task2ButtonActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(task2Panel);
        mainPanel.repaint(); mainPanel.revalidate();
    }//GEN-LAST:event_task2ButtonActionPerformed

    private void task3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task3ButtonActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(task3Panel);
        mainPanel.repaint(); mainPanel.revalidate();
    }//GEN-LAST:event_task3ButtonActionPerformed

    private void task1RunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task1RunButtonActionPerformed
        // TODO add your handling code here:
        SMethods tmp = new SMethods(constarray);
        String temp = "Исходный массив\n";
        for (int i = 0; i < constarray.length; i++)
        {
            temp += constarray[i] + "\t";
        }
        temp += "\nСумма всех четных элементов равна\n" + tmp.GetSum();
        task1TextArea.setText(temp);
    }//GEN-LAST:event_task1RunButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton task1Button;
    private javax.swing.JPanel task1Panel;
    private javax.swing.JButton task1RunButton;
    private javax.swing.JTextArea task1TextArea;
    private javax.swing.JButton task2Button;
    private javax.swing.JPanel task2Panel;
    private javax.swing.JButton task3Button;
    private javax.swing.JPanel task3Panel;
    // End of variables declaration//GEN-END:variables
}

