/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java4lab;
import javax.swing.JOptionPane;

/**
 *
 * @author Денис
 */
public class MainWindow extends javax.swing.JFrame {

    private final double[] constarray = {23, 1.3, 18, -6, 20, 1256};
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        task1Panel = new javax.swing.JPanel();
        task1RunButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        task1TextArea = new javax.swing.JTextArea();
        task2Panel = new javax.swing.JPanel();
        inputTextField = new javax.swing.JTextField();
        task2RunButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        task2TextArea = new javax.swing.JTextArea();
        task3Panel = new javax.swing.JPanel();
        task1Button = new javax.swing.JButton();
        task2Button = new javax.swing.JButton();
        task3Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setLayout(new java.awt.CardLayout());

        task1RunButton.setText("Run");
        task1RunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task1RunButtonActionPerformed(evt);
            }
        });

        task1TextArea.setColumns(20);
        task1TextArea.setRows(5);
        jScrollPane1.setViewportView(task1TextArea);

        javax.swing.GroupLayout task1PanelLayout = new javax.swing.GroupLayout(task1Panel);
        task1Panel.setLayout(task1PanelLayout);
        task1PanelLayout.setHorizontalGroup(
            task1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(task1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(task1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(task1PanelLayout.createSequentialGroup()
                        .addComponent(task1RunButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        task1PanelLayout.setVerticalGroup(
            task1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(task1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(task1RunButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(task1Panel, "card2");

        inputTextField.setText("23 1.3 -18 -6 20 1256");
        inputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputTextFieldKeyReleased(evt);
            }
        });

        task2RunButton.setText("Run");
        task2RunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task2RunButtonActionPerformed(evt);
            }
        });

        task2TextArea.setColumns(20);
        task2TextArea.setRows(5);
        jScrollPane2.setViewportView(task2TextArea);

        javax.swing.GroupLayout task2PanelLayout = new javax.swing.GroupLayout(task2Panel);
        task2Panel.setLayout(task2PanelLayout);
        task2PanelLayout.setHorizontalGroup(
            task2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, task2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(task2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(inputTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, task2PanelLayout.createSequentialGroup()
                        .addComponent(task2RunButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        task2PanelLayout.setVerticalGroup(
            task2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(task2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(task2RunButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(task2Panel, "card3");

        javax.swing.GroupLayout task3PanelLayout = new javax.swing.GroupLayout(task3Panel);
        task3Panel.setLayout(task3PanelLayout);
        task3PanelLayout.setHorizontalGroup(
            task3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        task3PanelLayout.setVerticalGroup(
            task3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        mainPanel.add(task3Panel, "card4");

        task1Button.setText("Задание A");
        task1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task1ButtonActionPerformed(evt);
            }
        });

        task2Button.setText("Задание B");
        task2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task2ButtonActionPerformed(evt);
            }
        });

        task3Button.setText("Задание C");
        task3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task3ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(task1Button)
                .addGap(88, 88, 88)
                .addComponent(task2Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(task3Button)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(task1Button)
                    .addComponent(task2Button)
                    .addComponent(task3Button))
                .addGap(18, 18, 18)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void task1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task1ButtonActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(task1Panel);
        mainPanel.repaint(); mainPanel.revalidate();
    }//GEN-LAST:event_task1ButtonActionPerformed

    private void task2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task2ButtonActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(task2Panel);
        mainPanel.repaint(); mainPanel.revalidate();
    }//GEN-LAST:event_task2ButtonActionPerformed

    private void task3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task3ButtonActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(task3Panel);
        mainPanel.repaint(); mainPanel.revalidate();
    }//GEN-LAST:event_task3ButtonActionPerformed

    private void task1RunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task1RunButtonActionPerformed
        // TODO add your handling code here:
        SMethods tmp = new SMethods(constarray);
        String temp = "Исходный массив\n";
        for (int i = 0; i < constarray.length; i++)
        {
            temp += constarray[i] + "\t";
        }
        temp += "\nСумма всех четных элементов равна\n" + tmp.GetSum();
        task1TextArea.setText(temp);
    }//GEN-LAST:event_task1RunButtonActionPerformed

    // checking input with KeyReleased is a BAD idea. I'm truly sorry for what 
    // i've done, but that's the task. i'd just use try/catch.
    private void inputTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextFieldKeyReleased
        // TODO add your handling code here:
        String input = inputTextField.getText();
        int inchar = evt.getKeyCode();
        // deleting everything except permitted symbols
        if (checkForAll(inchar) == false)
        {
            deleteLast(input);
            return;
        }
        // SPACE rules: space cannot be first, there can't be 2 spaces near
        if (((lastSymbol(input) == ' ') || (input.length() == 1)) && inchar == ' ')
        {
            deleteLast(input);
            return;
        }
        // MINUS rules: only after space of in the beggining
        if (!(lastSymbol(input) == ' ' || input.length() == 1) && (inchar == '-' || inchar == 109))
        {
            deleteLast(input);
            return;
        }
    }//GEN-LAST:event_inputTextFieldKeyReleased

    private void task2RunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task2RunButtonActionPerformed
        // TODO add your handling code here:
        String input = inputTextField.getText();
        int inputLength = input.length();
        if ((inputLength == 0) || (inputLength == 1 && input.contains("-")))
        {
            JOptionPane.showMessageDialog(null, "Необходимо ввести данные в верхнее текстовое поле!");
            return;
        }
        if (input.charAt(inputLength - 1) == '-')
            deleteLast(input);
        if (input.charAt(inputLength - 1) == ' ')
            deleteLast(input);
    }//GEN-LAST:event_task2RunButtonActionPerformed
    
    private char lastSymbol(String str)
    {
        if (str.length() > 1)
            return str.charAt(str.length() - 2);
        else
            return 'a'; // returning trash. that's ok though.
    }
    
    private void deleteLast(String str)
    {
        if (str != null && str.length() > 0) 
            str = str.substring(0, str.length() - 1);
        inputTextField.setText(str);
    }
    
    private boolean checkForAll(int a)
    {
        // checking for space, backspace, enter and "-"
        if (a == 32 || a == 8 || a == 10 || a == 45 || a == 109)
            return true;
        // checking for numbers from 0 to 9
        if (a >= 48 && a <=57)
            return true;
        // checking for numbers from 0 to 9 on numpad
        if (a >= 96 && a <= 105)
            return true;
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton task1Button;
    private javax.swing.JPanel task1Panel;
    private javax.swing.JButton task1RunButton;
    private javax.swing.JTextArea task1TextArea;
    private javax.swing.JButton task2Button;
    private javax.swing.JPanel task2Panel;
    private javax.swing.JButton task2RunButton;
    private javax.swing.JTextArea task2TextArea;
    private javax.swing.JButton task3Button;
    private javax.swing.JPanel task3Panel;
    // End of variables declaration//GEN-END:variables
}

